---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proxlab.net-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: www.proxlab.net
      http:
        paths:
          - path: /zabbix-server-fe
            pathType: Prefix
            backend:
              service:
                name: /zabbix-server-fe
                port:
                  number: 80
