---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proxlab.net-ingress
spec:
  ingressClassName: traefik # Questo ingress deve essere gestito da Trafeik
  rules:
    - host: www.proxlab.net
      http:
        paths:
          - path: /pod-prod-portale-1
            pathType: Prefix
            backend:
              service:
                name: service-prod-portale-1
                port:
                  number: 80
          - path: /pod-prod-portale-2
            pathType: Prefix
            backend:
              service:
                name: service-prod-portale-2
                port:
                  number: 80
          - path: /pod-prod-portale-3
            pathType: Prefix
            backend:
              service:
                name: service-prod-portale-3
                port:
                  number: 80
          - path: /pod-prod-portale-4
            pathType: Prefix
            backend:
              service:
                name: service-prod-portale-4
                port:
                  number: 80
