---
apiVersion: v1
kind: Service
metadata:
  name: service-prod-portale-1
  namespace: kubernetes-tomcat-infrastructure
spec:
  selector:
    app: deployment-app-prod-portale-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-prod-portale-2
  namespace: kubernetes-tomcat-infrastructure
spec:
  selector:
    app: deployment-app-prod-portale-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-prod-portale-3
  namespace: kubernetes-tomcat-infrastructure
spec:
  selector:
    app: deployment-app-prod-portale-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-prod-portale-4
  namespace: kubernetes-tomcat-infrastructure
spec:
  selector:
    app: deployment-app-prod-portale-4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

